home:
  servers:
    link1: "https://www.google.com"
about:
  servers:
    link1: "https://www.railstutorial.org/"
    link2: "https://www.railstutorial.org/book"
    link3: "http://screencasts.railstutorial.org/"
    link4: "http://rubyonrails.org/"
help:
  servers:
    link1: "https://www.railstutorial.org/help"
    link2: "https://www.railstutorial.org/book"
