home:
about:
    link1: "https://www.railstutorial.org/"
    link2: "https://www.railstutorial.org/book"
    link3: "http://screencasts.railstutorial.org/"
    link4: "http://rubyonrails.org/"
help:
    link1: "https://www.railstutorial.org/help"
    link2: "https://www.railstutorial.org/book"
book:
  link: "https://www.railstutorial.org/"
  author_link: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
